name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Test 1
      run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_expected.txt
      
    - name: Compare output
      run: diff test_data/test1_input.txt test_data/test1_expected.txt

  test2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Test 2
      run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_expected.txt
      
    - name: Compare output
      run: diff test_data/test2_input.txt test_data/test2_expected.txt

  test3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Test 3
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_expected.txt
      
    - name: Compare output

    
      run: diff test_data/test3_input.txt test_data/test3_expected.txt
